FROM python:3.7-alpine

RUN mkdir -p /app
WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY main.py /app
COPY messages_pb2.py /app

EXPOSE 8080

CMD ["gunicorn", "-b", "0.0.0.0:8080", "-w 4", "main:app"]

