apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: logins
  namespace: kafka
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 1
  replicas: 1

---

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: seen
  namespace: kafka
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 1
  replicas: 1
